### ISSUE TITLE
Error rendering world

### ISSUE THREAD

**Issue by ekrumme** [ferrybig/Minecraft-Overview-Mapper#2]
Is there a version that is not supported by the renderer? I was able to create a map using a small test world created in 1.13.2 but running the renderer on an older map created several years ago and updated to 1.13.2 I get a java Exception dump.

Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: me.ferrybig.java.minecraft.nbt.ByteArrayTag cannot be cast to me.ferrybig.java.minecraft.nbt.IntArrayTag

full error log
[error.log](https://github.com/ferrybig/Minecraft-Overview-Mapper/files/3045317/error.log)

**Comment by ferrybig** [comment]
I have seen this error in the past with 1.12 or older worlds, or 1.13.2 worlds that still have some old chunks left.

During the development I actually never tested those older chunks, since I purposely made it for 1.13 worlds, since no renders existed for those worlds.

One workaround for that you an do is  migrating your world to 1.13 either by going to single player and pressing "optimize world" in the "edit world" menu, or by starting your Minecraft server with the option [ `--forceUpgrade](https://www.reddit.com/r/Minecraft/comments/8zxzbl/server_owners_how_to_optimize_your_world_for_113/)` at the end of the command line. This also increases performance, as your Minecraft no longer has to convert chunk when you are playing.

Another solution is to wait till I build in support for chunks of older versions.

**Comment by ekrumme** [comment]
Thank you, forcing the upgrade worked. I thought my world had already been updated because I had loaded it but choosing the 'Optimize World' option allowed your program to work on my world.
